//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voltmeter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voltmeter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device polling loop started.
        /// </summary>
        internal static string Device_Polling_Loop_Started {
            get {
                return ResourceManager.GetString("Device_Polling_Loop_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device polling loop stopped.
        /// </summary>
        internal static string Device_Polling_Loop_Stopped {
            get {
                return ResourceManager.GetString("Device_Polling_Loop_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device takes more time to handle data request, than given polling interval [T = {0:c}]:.
        /// </summary>
        internal static string Device_Too_Slow_0 {
            get {
                return ResourceManager.GetString("Device_Too_Slow_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave signal device emulation.
        /// </summary>
        internal static string Emulated_Device_Description {
            get {
                return ResourceManager.GetString("Emulated_Device_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string Log_Exception_0 {
            get {
                return ResourceManager.GetString("Log_Exception_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}.
        /// </summary>
        internal static string Log_Message_0 {
            get {
                return ResourceManager.GetString("Log_Message_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NESTED EXCEPTION.
        /// </summary>
        internal static string Log_NestedException {
            get {
                return ResourceManager.GetString("Log_NestedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace:.
        /// </summary>
        internal static string Log_StackTrace {
            get {
                return ResourceManager.GetString("Log_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression.
        /// </summary>
        internal static string StaticReflection_InvalidExpression {
            get {
                return ResourceManager.GetString("StaticReflection_InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time = {0}.
        /// </summary>
        internal static string TimeStats_Avg_0 {
            get {
                return ResourceManager.GetString("TimeStats_Avg_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum time = {0}.
        /// </summary>
        internal static string TimeStats_Max_0 {
            get {
                return ResourceManager.GetString("TimeStats_Max_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum time = {0}.
        /// </summary>
        internal static string TimeStats_Min_0 {
            get {
                return ResourceManager.GetString("TimeStats_Min_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples = {0}.
        /// </summary>
        internal static string TimeStats_Samples_0 {
            get {
                return ResourceManager.GetString("TimeStats_Samples_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Device &quot;{0}&quot; is plugged.
        /// </summary>
        internal static string USB_Device_Plugged_0 {
            get {
                return ResourceManager.GetString("USB_Device_Plugged_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB device polling loop.
        /// </summary>
        internal static string USB_Device_Polling_Loop {
            get {
                return ResourceManager.GetString("USB_Device_Polling_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Device &quot;{0}&quot; is unplugged.
        /// </summary>
        internal static string USB_Device_Unplugged_0 {
            get {
                return ResourceManager.GetString("USB_Device_Unplugged_0", resourceCulture);
            }
        }
    }
}
