//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voltmeter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnitNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnitNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voltmeter.Resources.UnitNames", typeof(UnitNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ampere.
        /// </summary>
        internal static string Current_Ampere {
            get {
                return ResourceManager.GetString("Current_Ampere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Current_Ampere_Abbr {
            get {
                return ResourceManager.GetString("Current_Ampere_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to micro-amp.
        /// </summary>
        internal static string Current_microAmpere {
            get {
                return ResourceManager.GetString("Current_microAmpere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to µA.
        /// </summary>
        internal static string Current_microAmpere_Abbr {
            get {
                return ResourceManager.GetString("Current_microAmpere_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milli-amp.
        /// </summary>
        internal static string Current_milliAmpere {
            get {
                return ResourceManager.GetString("Current_milliAmpere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mA.
        /// </summary>
        internal static string Current_milliAmpere_Abbr {
            get {
                return ResourceManager.GetString("Current_milliAmpere_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current_Type {
            get {
                return ResourceManager.GetString("Current_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilo-watt-hour.
        /// </summary>
        internal static string Energy_kiloWattHour {
            get {
                return ResourceManager.GetString("Energy_kiloWattHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kW·h.
        /// </summary>
        internal static string Energy_kiloWattHour_Abbr {
            get {
                return ResourceManager.GetString("Energy_kiloWattHour_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milli-watt-second.
        /// </summary>
        internal static string Energy_milliWattSec {
            get {
                return ResourceManager.GetString("Energy_milliWattSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mW·s.
        /// </summary>
        internal static string Energy_milliWattSec_Abbr {
            get {
                return ResourceManager.GetString("Energy_milliWattSec_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Energy_Type {
            get {
                return ResourceManager.GetString("Energy_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watt-hour.
        /// </summary>
        internal static string Energy_WattHour {
            get {
                return ResourceManager.GetString("Energy_WattHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W·h.
        /// </summary>
        internal static string Energy_WattHour_Abbr {
            get {
                return ResourceManager.GetString("Energy_WattHour_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watt-second.
        /// </summary>
        internal static string Energy_WattSec {
            get {
                return ResourceManager.GetString("Energy_WattSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W·s.
        /// </summary>
        internal static string Energy_WattSec_Abbr {
            get {
                return ResourceManager.GetString("Energy_WattSec_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilo-watt.
        /// </summary>
        internal static string Power_kiloWatt {
            get {
                return ResourceManager.GetString("Power_kiloWatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kW.
        /// </summary>
        internal static string Power_kiloWatt_Abbr {
            get {
                return ResourceManager.GetString("Power_kiloWatt_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milli-watt.
        /// </summary>
        internal static string Power_milliWatt {
            get {
                return ResourceManager.GetString("Power_milliWatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mW.
        /// </summary>
        internal static string Power_milliWatt_Abbr {
            get {
                return ResourceManager.GetString("Power_milliWatt_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Power.
        /// </summary>
        internal static string Power_Type {
            get {
                return ResourceManager.GetString("Power_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watt.
        /// </summary>
        internal static string Power_Watt {
            get {
                return ResourceManager.GetString("Power_Watt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string Power_Watt_Abbr {
            get {
                return ResourceManager.GetString("Power_Watt_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilo-ohm.
        /// </summary>
        internal static string Resistance_kiloOhm {
            get {
                return ResourceManager.GetString("Resistance_kiloOhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kΩ.
        /// </summary>
        internal static string Resistance_kiloOhm_Abbr {
            get {
                return ResourceManager.GetString("Resistance_kiloOhm_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milli-ohm.
        /// </summary>
        internal static string Resistance_milliOhm {
            get {
                return ResourceManager.GetString("Resistance_milliOhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mΩ.
        /// </summary>
        internal static string Resistance_milliOhm_Abbr {
            get {
                return ResourceManager.GetString("Resistance_milliOhm_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohm.
        /// </summary>
        internal static string Resistance_Ohm {
            get {
                return ResourceManager.GetString("Resistance_Ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ω.
        /// </summary>
        internal static string Resistance_Ohm_Abbr {
            get {
                return ResourceManager.GetString("Resistance_Ohm_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance.
        /// </summary>
        internal static string Resistance_Type {
            get {
                return ResourceManager.GetString("Resistance_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilo-volt.
        /// </summary>
        internal static string Voltage_kiloVolt {
            get {
                return ResourceManager.GetString("Voltage_kiloVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kV.
        /// </summary>
        internal static string Voltage_kiloVolt_Abbr {
            get {
                return ResourceManager.GetString("Voltage_kiloVolt_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milli-volt.
        /// </summary>
        internal static string Voltage_milliVolt {
            get {
                return ResourceManager.GetString("Voltage_milliVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mV.
        /// </summary>
        internal static string Voltage_milliVolt_Abbr {
            get {
                return ResourceManager.GetString("Voltage_milliVolt_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        internal static string Voltage_Type {
            get {
                return ResourceManager.GetString("Voltage_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volt.
        /// </summary>
        internal static string Voltage_Volt {
            get {
                return ResourceManager.GetString("Voltage_Volt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string Voltage_Volt_Abbr {
            get {
                return ResourceManager.GetString("Voltage_Volt_Abbr", resourceCulture);
            }
        }
    }
}
