//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voltmeter.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voltmeter.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string About_Title_0 {
            get {
                return ResourceManager.GetString("About_Title_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string About_Version_0 {
            get {
                return ResourceManager.GetString("About_Version_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the readings be recalculated using new resistance value?.
        /// </summary>
        internal static string Adjust_Values_For_Resistance {
            get {
                return ResourceManager.GetString("Adjust_Values_For_Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the readings be recalculated using new voltage scale factor?.
        /// </summary>
        internal static string Adjust_Values_For_VoltageScale {
            get {
                return ResourceManager.GetString("Adjust_Values_For_VoltageScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is available.
        /// </summary>
        internal static string Device_Available {
            get {
                return ResourceManager.GetString("Device_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is unavailable.
        /// </summary>
        internal static string Device_Unavailable {
            get {
                return ResourceManager.GetString("Device_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load applicatoin settings.
        /// </summary>
        internal static string Load_Settings_Error {
            get {
                return ResourceManager.GetString("Load_Settings_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save application settings.
        /// </summary>
        internal static string Save_Settings_Error {
            get {
                return ResourceManager.GetString("Save_Settings_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled application exception. Application shut down..
        /// </summary>
        internal static string Unhandled_Exception {
            get {
                return ResourceManager.GetString("Unhandled_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected application error occurred. Please check EventLog records of &apos;{0}&apos; for more details..
        /// </summary>
        internal static string Unhandled_Exception_Message_0 {
            get {
                return ResourceManager.GetString("Unhandled_Exception_Message_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
